### ISSUE TITLE
Which ROS GUI version should I use?

### ISSUE THREAD

**Issue by SilviaZirino** [ucsdarclab/dVRL#8]
Hello,

I'm trying to set up the system following the README file, but I have some doubts.

Firstly, which method should I use to enable the GUI within Docker? I was thinking about using X server and in particular one of the first two ways, but which one is the best?

Then, do I need to previously install ROS in order to just open vrep? If yes, can I use ROS Melodic?

Finally, if I have to work with macOS, can I use Docker? Are there any particular changes that I need to make regarding files or new things that I should add?

Thanks in advance!

**Comment by bango123** [comment]
To enable the GUI I usually use what ros describes the as the “reckless” way (this is the first method). Any method should work however.

No ROS is required to run this, I just referenced the ROS tutorial for enabling GUI. 

To run on mac, I have never tested it. I believe a the main challenge (as others have pointed out ) will be with the nvidia docker since macs don’t use nvidia. Please refer to the other issue posts https://github.com/ucsdarclab/dVRL/issues/3# for ideas on how to run it on Mac.
